# Generated By lexicon-dsa CLI tool.
# Author: Saptak Sengupta(deeps.sengupta@gmail.com)
# Github: https://github.com/saptaksengupta/

class demoClass:
    def __init__(self):
        self.demoVar = "Generated by Lexicon-dsa cli Template generator."

    def demoMethod(self):
        print(self.demoVar)


if __name__ == "__main__":
    instance = demoClass()
    instance.demoMethod()
