// Generated By lexicon-dsa CLI tool.
// Author: Saptak Sengupta(deeps.sengupta@gmail.com)
// Github: https://github.com/saptaksengupta/

public class Template {

    // Complete the countingValleys function below.
    static String demoFunction() {
        return "Generated by Lexicon-dsa cli Template generator.";
    }

    public static void main(String[] args) {
        String result = demoFunction();
        System.out.println(result);
    }
}