class demoClass:
    def __init__(self):
        self.demoVar = "Generated by Lexicon."

    def demoMethod(self):
        print(self.demoVar)


if __name__ == "__main__":
    instance = demoClass()
    instance.demoMethod()
