'use strict';
// Generated By lexicon-dsa CLI tool.
// Author: Saptak Sengupta(deeps.sengupta@gmail.com)
// Github: https://github.com/saptaksengupta/


// Complete the demoFunction function below.
// You should change the name accordinglly.
function demoFunction() {
    return "Generated by @saptak/lexicon cli Template generator.";
}

function main() {
    let result = demoFunction();
    console.log(result);
}

main();

