'use strict';

// Generated By lexicon-dsa CLI tool.
// Author: Saptak Sengupta(deeps.sengupta@gmail.com)
// Github: https://github.com/saptaksengupta/

function demoFunction() {
    return "Generated by Lexicon-dsa cli Template generator.";
}

function main() {
    let result = demoFunction();
    console.log(result);
}

main();

